apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-persistent-volume
  labels:
    type: local
  namespace: ${DEMO_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/vda1/rabbitmq
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
