apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-persistent-volume-claim
  namespace: ${DEMO_NAMESPACE}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: rabbitmq-persistent-volume
