apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: senzing-persistent-volume-claim
  namespace: ${DEMO_NAMESPACE}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: senzing-persistent-volume
