apiVersion: v1
kind: PersistentVolume
metadata:
  name: senzing-persistent-volume
  namespace: ${DEMO_NAMESPACE}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: /disk2/nfspv
    server: bsr-openshift-nfs-0
  persistentVolumeReclaimPolicy: Retain
