apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints

metadata:
  name: senzing-security-context-constraint-runasany
  namespace: ${DEMO_NAMESPACE}

allowPrivilegeEscalation: true
allowPrivilegedContainer: true

fsGroup:
  type: RunAsAny

groups:
- system:cluster-admins

readOnlyRootFilesystem: false

runAsUser:
  type: RunAsAny

seLinuxContext:
  type: MustRunAs

supplementalGroups:
  type: RunAsAny

volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
