image:
  registry: ${DOCKER_REGISTRY_URL}

imagePullSecrets:
  - name: ${DOCKER_REGISTRY_SECRET}

ingress:
  enabled: true
  hosts:
    - host: senzing-configurator.local
      paths:
        - /

rbacEnabled: true

securityContext:
  enabled: true
  runAsUser: ${SENZING_RUN_AS_USER}
  runAsGroup: ${SENZING_RUN_AS_GROUP}
  fsGroup: ${SENZING_FS_GROUP}

senzing:
  databaseUrl: "db2://db2inst1:db2inst1@${DEMO_PREFIX}-senzing-ibm-db2:50000/G2"
  persistentVolumeClaim: senzing-persistent-volume-claim
  subcommand: service
